# Generated by Django 4.1.1 on 2022-10-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_weight_alter_food_quantity'),
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='foods',
            field=models.ManyToManyField(to='food.food'),
        ),
    ]
