# Generated by Django 4.1.1 on 2022-10-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0002_director_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='foods',
        ),
    ]
