# Generated by Django 4.1.1 on 2022-10-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_foods'),
        ('food', '0002_food_weight_alter_food_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='school',
            field=models.ManyToManyField(to='schools.school'),
        ),
    ]
